# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

# $Id: Makefile.am,v 1.3 2000/02/07 18:52:00 alex Exp $


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/mpc
pkglibdir = $(libdir)/mpc
pkgincludedir = $(includedir)/mpc

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = /usr/local/bin/autoconf
AUTOMAKE = /usr/local/bin/automake
AUTOHEADER = /usr/local/bin/autoheader

INSTALL = @INSTALL@
INSTALL_PROGRAM = @INSTALL_PROGRAM@ $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = @INSTALL_DATA@
INSTALL_SCRIPT = @INSTALL_SCRIPT@
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i386-unknown-freebsd3.4
build_triplet = i386-unknown-freebsd3.4
host_alias = i386-unknown-freebsd3.4
host_triplet = i386-unknown-freebsd3.4
target_alias = i386-unknown-freebsd3.4
target_triplet = i386-unknown-freebsd3.4
AR = /usr/bin/ar
AS = /usr/bin/as
AUTOCONF = /usr/local/bin/autoconf
AUTOHEADER = /usr/local/bin/autoheader
AUTOMAKE = /usr/local/bin/automake
CAT = /bin/cat
CC = gcc
CHMOD = /bin/chmod
CP = /bin/cp
CPP = gcc -E
CSH = /bin/csh
CUT = /usr/bin/cut
CXX = c++
CXXCPP = c++ -E
DEBUG_FLAGS =  -DMPC_STATS
ECHO = /bin/echo
FALSE = /usr/bin/false
GENSETDEFS = /usr/bin/gensetdefs
GREP = /usr/bin/grep
HOST1 = bench1
HOST2 = bench2
HOSTNAME = /bin/hostname
ID = /usr/bin/id
KERNEL_FILE = /kernel
KLDLOAD = /sbin/kldload
KLDSTAT = /sbin/kldstat
KLDUNLOAD = /sbin/kldunload
LD = /usr/bin/ld
LEX = flex
LIBXFORMS = -lxforms
LIMITS = /usr/bin/limits
LN_S = ln -s
LOOPBACK = 
LS = /bin/ls
M4 = /usr/bin/m4
MAKEDEPEND = /usr/X11R6.3/bin/makedepend
MAKEINFO = /usr/bin/makeinfo
MKDIR = /bin/mkdir
MKNOD = /sbin/mknod
MODLOAD = /sbin/modload
MODSTAT = /usr/bin/modstat
MODUNLOAD = /sbin/modunload
MV = /bin/mv
NM = /usr/bin/nm
PACKAGE = mpc
PERL = /usr/bin/perl5
PWD = /eowyn_home/alex/cvs/alex/MPC-OS-5
RANLIB = ranlib
RM = /bin/rm
RPCGEN = /usr/bin/rpcgen
RSH = /usr/bin/rsh
SED = /usr/bin/sed
SMP_FLAGS_1 = -I/usr/include -I/sys
SMP_FLAGS_2 = -D_SMP_SUPPORT
SMP_FLAGS_3 = -elf
TEST = /bin/test
TOUCH = /usr/bin/touch
TR = /usr/bin/tr
TRUE = /usr/bin/true
VERSION = 5.3
WC = /usr/bin/wc
WITH_KLD = yes
WITH_STABS = yes
WORKAROUND_FLAGS = -DPCIDDC2ndRun
XHOST = /usr/X11R6.3/bin/xhost
XTERM = /usr/X11R6.3/bin/xterm
X_HOSTS = bench1/bench2
X_SHELL = /usr/local/bin/zsh
YACC = /usr/bin/yacc
ZSH = /usr/local/bin/zsh

noinst_PROGRAMS = addlpe receivelpe testsend testrecv testsend2                   testrecv2 testsendv testrecvv mmapdev testuseraccess                   testsend2wait testrecv2wait vmtest testsendv-prot 		  testrecvv-prot testselectnotice testsendv2 testrecvv2 		  testlatenceslr testpvmslr


testuseraccess_LDADD = ../src/libuseraccess.a

CFLAGS =  -g -I/usr/include -I/sys -D_SMP_SUPPORT
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_CLEAN_FILES = 
PROGRAMS =  $(noinst_PROGRAMS)


DEFS =  -DYYTEXT_POINTER=1 -DSTDC_HEADERS=1 -DKERNEL_FILE=\"/kernel\" -D_SMP_SUPPORT=1 -DWITH_STABS_PCIBUS_SET=1 -DWITH_KLD=1 -D_WITHOUT_DDSCP=1 -D_WITHOUT_MONITOR=1 -DWITHOUT_LOOPBACK=1  -I. -I$(srcdir) 
CPPFLAGS = 
LDFLAGS = 
LIBS = 
X_CFLAGS =  -I/usr/X11R6/include
X_LIBS =  -L/usr/X11R6/lib
X_EXTRA_LIBS = 
X_PRE_LIBS =  -lSM -lICE
addlpe_SOURCES = addlpe.c
addlpe_OBJECTS =  addlpe.o
addlpe_LDADD = $(LDADD)
addlpe_DEPENDENCIES = 
addlpe_LDFLAGS = 
receivelpe_SOURCES = receivelpe.c
receivelpe_OBJECTS =  receivelpe.o
receivelpe_LDADD = $(LDADD)
receivelpe_DEPENDENCIES = 
receivelpe_LDFLAGS = 
testsend_SOURCES = testsend.c
testsend_OBJECTS =  testsend.o
testsend_LDADD = $(LDADD)
testsend_DEPENDENCIES = 
testsend_LDFLAGS = 
testrecv_SOURCES = testrecv.c
testrecv_OBJECTS =  testrecv.o
testrecv_LDADD = $(LDADD)
testrecv_DEPENDENCIES = 
testrecv_LDFLAGS = 
testsend2_SOURCES = testsend2.c
testsend2_OBJECTS =  testsend2.o
testsend2_LDADD = $(LDADD)
testsend2_DEPENDENCIES = 
testsend2_LDFLAGS = 
testrecv2_SOURCES = testrecv2.c
testrecv2_OBJECTS =  testrecv2.o
testrecv2_LDADD = $(LDADD)
testrecv2_DEPENDENCIES = 
testrecv2_LDFLAGS = 
testsendv_SOURCES = testsendv.c
testsendv_OBJECTS =  testsendv.o
testsendv_LDADD = $(LDADD)
testsendv_DEPENDENCIES = 
testsendv_LDFLAGS = 
testrecvv_SOURCES = testrecvv.c
testrecvv_OBJECTS =  testrecvv.o
testrecvv_LDADD = $(LDADD)
testrecvv_DEPENDENCIES = 
testrecvv_LDFLAGS = 
mmapdev_SOURCES = mmapdev.c
mmapdev_OBJECTS =  mmapdev.o
mmapdev_LDADD = $(LDADD)
mmapdev_DEPENDENCIES = 
mmapdev_LDFLAGS = 
testuseraccess_SOURCES = testuseraccess.c
testuseraccess_OBJECTS =  testuseraccess.o
testuseraccess_DEPENDENCIES =  ../src/libuseraccess.a
testuseraccess_LDFLAGS = 
testsend2wait_SOURCES = testsend2wait.c
testsend2wait_OBJECTS =  testsend2wait.o
testsend2wait_LDADD = $(LDADD)
testsend2wait_DEPENDENCIES = 
testsend2wait_LDFLAGS = 
testrecv2wait_SOURCES = testrecv2wait.c
testrecv2wait_OBJECTS =  testrecv2wait.o
testrecv2wait_LDADD = $(LDADD)
testrecv2wait_DEPENDENCIES = 
testrecv2wait_LDFLAGS = 
vmtest_SOURCES = vmtest.c
vmtest_OBJECTS =  vmtest.o
vmtest_LDADD = $(LDADD)
vmtest_DEPENDENCIES = 
vmtest_LDFLAGS = 
testsendv_prot_SOURCES = testsendv-prot.c
testsendv_prot_OBJECTS =  testsendv-prot.o
testsendv_prot_LDADD = $(LDADD)
testsendv_prot_DEPENDENCIES = 
testsendv_prot_LDFLAGS = 
testrecvv_prot_SOURCES = testrecvv-prot.c
testrecvv_prot_OBJECTS =  testrecvv-prot.o
testrecvv_prot_LDADD = $(LDADD)
testrecvv_prot_DEPENDENCIES = 
testrecvv_prot_LDFLAGS = 
testselectnotice_SOURCES = testselectnotice.c
testselectnotice_OBJECTS =  testselectnotice.o
testselectnotice_LDADD = $(LDADD)
testselectnotice_DEPENDENCIES = 
testselectnotice_LDFLAGS = 
testsendv2_SOURCES = testsendv2.c
testsendv2_OBJECTS =  testsendv2.o
testsendv2_LDADD = $(LDADD)
testsendv2_DEPENDENCIES = 
testsendv2_LDFLAGS = 
testrecvv2_SOURCES = testrecvv2.c
testrecvv2_OBJECTS =  testrecvv2.o
testrecvv2_LDADD = $(LDADD)
testrecvv2_DEPENDENCIES = 
testrecvv2_LDFLAGS = 
testlatenceslr_SOURCES = testlatenceslr.c
testlatenceslr_OBJECTS =  testlatenceslr.o
testlatenceslr_LDADD = $(LDADD)
testlatenceslr_DEPENDENCIES = 
testlatenceslr_LDFLAGS = 
testpvmslr_SOURCES = testpvmslr.c
testpvmslr_OBJECTS =  testpvmslr.o
testpvmslr_LDADD = $(LDADD)
testpvmslr_DEPENDENCIES = 
testpvmslr_LDFLAGS = 
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = tar
GZIP_ENV = --best
DEP_FILES =  .deps/addlpe.P .deps/mmapdev.P .deps/receivelpe.P \
.deps/testlatenceslr.P .deps/testpvmslr.P .deps/testrecv.P \
.deps/testrecv2.P .deps/testrecv2wait.P .deps/testrecvv-prot.P \
.deps/testrecvv.P .deps/testrecvv2.P .deps/testselectnotice.P \
.deps/testsend.P .deps/testsend2.P .deps/testsend2wait.P \
.deps/testsendv-prot.P .deps/testsendv.P .deps/testsendv2.P \
.deps/testuseraccess.P .deps/vmtest.P
SOURCES = addlpe.c receivelpe.c testsend.c testrecv.c testsend2.c testrecv2.c testsendv.c testrecvv.c mmapdev.c testuseraccess.c testsend2wait.c testrecv2wait.c vmtest.c testsendv-prot.c testrecvv-prot.c testselectnotice.c testsendv2.c testrecvv2.c testlatenceslr.c testpvmslr.c
OBJECTS = addlpe.o receivelpe.o testsend.o testrecv.o testsend2.o testrecv2.o testsendv.o testrecvv.o mmapdev.o testuseraccess.o testsend2wait.o testrecv2wait.o vmtest.o testsendv-prot.o testrecvv-prot.o testselectnotice.o testsendv2.o testrecvv2.o testlatenceslr.o testpvmslr.o

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .o .s
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu examples/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-noinstPROGRAMS:

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)

distclean-noinstPROGRAMS:

maintainer-clean-noinstPROGRAMS:

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

addlpe: $(addlpe_OBJECTS) $(addlpe_DEPENDENCIES)
	@rm -f addlpe
	$(LINK) $(addlpe_LDFLAGS) $(addlpe_OBJECTS) $(addlpe_LDADD) $(LIBS)

receivelpe: $(receivelpe_OBJECTS) $(receivelpe_DEPENDENCIES)
	@rm -f receivelpe
	$(LINK) $(receivelpe_LDFLAGS) $(receivelpe_OBJECTS) $(receivelpe_LDADD) $(LIBS)

testsend: $(testsend_OBJECTS) $(testsend_DEPENDENCIES)
	@rm -f testsend
	$(LINK) $(testsend_LDFLAGS) $(testsend_OBJECTS) $(testsend_LDADD) $(LIBS)

testrecv: $(testrecv_OBJECTS) $(testrecv_DEPENDENCIES)
	@rm -f testrecv
	$(LINK) $(testrecv_LDFLAGS) $(testrecv_OBJECTS) $(testrecv_LDADD) $(LIBS)

testsend2: $(testsend2_OBJECTS) $(testsend2_DEPENDENCIES)
	@rm -f testsend2
	$(LINK) $(testsend2_LDFLAGS) $(testsend2_OBJECTS) $(testsend2_LDADD) $(LIBS)

testrecv2: $(testrecv2_OBJECTS) $(testrecv2_DEPENDENCIES)
	@rm -f testrecv2
	$(LINK) $(testrecv2_LDFLAGS) $(testrecv2_OBJECTS) $(testrecv2_LDADD) $(LIBS)

testsendv: $(testsendv_OBJECTS) $(testsendv_DEPENDENCIES)
	@rm -f testsendv
	$(LINK) $(testsendv_LDFLAGS) $(testsendv_OBJECTS) $(testsendv_LDADD) $(LIBS)

testrecvv: $(testrecvv_OBJECTS) $(testrecvv_DEPENDENCIES)
	@rm -f testrecvv
	$(LINK) $(testrecvv_LDFLAGS) $(testrecvv_OBJECTS) $(testrecvv_LDADD) $(LIBS)

mmapdev: $(mmapdev_OBJECTS) $(mmapdev_DEPENDENCIES)
	@rm -f mmapdev
	$(LINK) $(mmapdev_LDFLAGS) $(mmapdev_OBJECTS) $(mmapdev_LDADD) $(LIBS)

testsend2wait: $(testsend2wait_OBJECTS) $(testsend2wait_DEPENDENCIES)
	@rm -f testsend2wait
	$(LINK) $(testsend2wait_LDFLAGS) $(testsend2wait_OBJECTS) $(testsend2wait_LDADD) $(LIBS)

testrecv2wait: $(testrecv2wait_OBJECTS) $(testrecv2wait_DEPENDENCIES)
	@rm -f testrecv2wait
	$(LINK) $(testrecv2wait_LDFLAGS) $(testrecv2wait_OBJECTS) $(testrecv2wait_LDADD) $(LIBS)

vmtest: $(vmtest_OBJECTS) $(vmtest_DEPENDENCIES)
	@rm -f vmtest
	$(LINK) $(vmtest_LDFLAGS) $(vmtest_OBJECTS) $(vmtest_LDADD) $(LIBS)

testsendv-prot: $(testsendv_prot_OBJECTS) $(testsendv_prot_DEPENDENCIES)
	@rm -f testsendv-prot
	$(LINK) $(testsendv_prot_LDFLAGS) $(testsendv_prot_OBJECTS) $(testsendv_prot_LDADD) $(LIBS)

testrecvv-prot: $(testrecvv_prot_OBJECTS) $(testrecvv_prot_DEPENDENCIES)
	@rm -f testrecvv-prot
	$(LINK) $(testrecvv_prot_LDFLAGS) $(testrecvv_prot_OBJECTS) $(testrecvv_prot_LDADD) $(LIBS)

testselectnotice: $(testselectnotice_OBJECTS) $(testselectnotice_DEPENDENCIES)
	@rm -f testselectnotice
	$(LINK) $(testselectnotice_LDFLAGS) $(testselectnotice_OBJECTS) $(testselectnotice_LDADD) $(LIBS)

testsendv2: $(testsendv2_OBJECTS) $(testsendv2_DEPENDENCIES)
	@rm -f testsendv2
	$(LINK) $(testsendv2_LDFLAGS) $(testsendv2_OBJECTS) $(testsendv2_LDADD) $(LIBS)

testrecvv2: $(testrecvv2_OBJECTS) $(testrecvv2_DEPENDENCIES)
	@rm -f testrecvv2
	$(LINK) $(testrecvv2_LDFLAGS) $(testrecvv2_OBJECTS) $(testrecvv2_LDADD) $(LIBS)

testlatenceslr: $(testlatenceslr_OBJECTS) $(testlatenceslr_DEPENDENCIES)
	@rm -f testlatenceslr
	$(LINK) $(testlatenceslr_LDFLAGS) $(testlatenceslr_OBJECTS) $(testlatenceslr_LDADD) $(LIBS)

testpvmslr: $(testpvmslr_OBJECTS) $(testpvmslr_DEPENDENCIES)
	@rm -f testpvmslr
	$(LINK) $(testpvmslr_LDFLAGS) $(testpvmslr_OBJECTS) $(testpvmslr_LDADD) $(LIBS)

tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = examples

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu examples/Makefile
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done

DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)

-include $(DEP_FILES)

mostlyclean-depend:

clean-depend:

distclean-depend:
	-rm -rf .deps

maintainer-clean-depend:

%.o: %.c
	@echo '$(COMPILE) -c $<'; \
	$(COMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-cp .deps/$(*F).pp .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm .deps/$(*F).pp

%.lo: %.c
	@echo '$(LTCOMPILE) -c $<'; \
	$(LTCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
	  < .deps/$(*F).pp > .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm -f .deps/$(*F).pp
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am:
uninstall: uninstall-am
all-am: Makefile $(PROGRAMS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-noinstPROGRAMS mostlyclean-compile \
		mostlyclean-tags mostlyclean-depend mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-noinstPROGRAMS clean-compile clean-tags clean-depend \
		clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-noinstPROGRAMS distclean-compile distclean-tags \
		distclean-depend distclean-generic clean-am

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-noinstPROGRAMS \
		maintainer-clean-compile maintainer-clean-tags \
		maintainer-clean-depend maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-noinstPROGRAMS distclean-noinstPROGRAMS \
clean-noinstPROGRAMS maintainer-clean-noinstPROGRAMS \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile tags mostlyclean-tags distclean-tags \
clean-tags maintainer-clean-tags distdir mostlyclean-depend \
distclean-depend clean-depend maintainer-clean-depend info-am info \
dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
install-exec install-data-am install-data install-am install \
uninstall-am uninstall all-redirect all-am all installdirs \
mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean

testuseraccess: ../src/libuseraccess.a

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
